### ISSUE TITLE
Error: ENOENT: no such file or directory, open './build/b64.txt'

### ISSUE THREAD

**Issue by max-samusevich** [Acuao/base64-advanced-cli#3]
Hello, @Acuao!

I've already used your utility few month ago and that time it could create output path folders if they didn't exist. In my case I have no "build" folder in my project until I need it and I want b64 to create this folder when it encodes an image. It worked but today i copy-pasted the command I used last time in the same project, and now I get an error `Error: ENOENT: no such file or directory, open './build/b64.txt'`.

I've already met this error last time but this was caused by a mistyped space in the beginning of the terminal line. When I fixed it, b64 started to create folder that didn't exist.

Today I tried to run b64 when the destination folder existed, and it worked fine but it fails if the folder didn't exist. 

Could you explain, please, if b64 should create folders recursively, that don't exist, or not? I'm almost sure it worked :) Maybe you could guide me towards the proper fix of the error.

Anyway thank you for b64, it's very convenient and fast, and increase my work pace ❤

**Comment by max-samusevich** [comment]
@Acuao, thanks for such a fast response! I appreciate that

Was b64 able to create non-existing folders before?
Is your latest code finished? Will you update the package as a release so it'll be possible to update b64 through npm?

**Comment by Acuao** [comment]
Hello @max-samusevich ,

First thanks for your interest in the project, this is much apreciated.

No, b64 was not meant to do that, but i think that it is a good improvement for the tool, this is why i decided to include this new feature in the project.

I already made a new release, but i just realized it works only if you don't use the `--html`, i'll have to fix that 😅


Again, thank you for creating this issue, it helps the project a lot ! 👍

**Comment by Acuao** [comment]
@max-samusevich 
v1.3.1 released : On my side all seems OK for now.

Feel free to open new issues if you encounter issues of have other improvement ideas.

**Comment by max-samusevich** [comment]
@Acuao, i've already updated and tested the package. It works awesome, exactly as I wanted it to! Thanks again for being so attentive and open. You are breathtaking⚡

If I have an idea for improvement or stumble upon a problem, I'll be sure to let you know :)
